# Generated by Django 4.1 on 2022-09-03 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('dtype', models.CharField(choices=[('post', '포스트'), ('game', '게임'), ('team', '팀')], default='post', max_length=10)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('game_name', models.CharField(max_length=128)),
                ('game_location', models.CharField(max_length=128)),
                ('room_name', models.CharField(max_length=128)),
                ('joined_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.feed',),
        ),
    ]
